version: '3'

services:
  mongodb-api:
    image: mongo:3.2.4
    container_name: "mongodb-sportyapp"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "sportyapp-api"
    ports:
    - 8443:8443
    - 8080:8080
    depends_on:
      - mongodb-api
    links:
      - mongodb-api
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb-api
      - SPRING_DATA_MONGODB_DATABASE=sportyapp